const users = [
  { name: "John Doe", email: "john.doe@example.com", role: "Admin" },
  { name: "Jane Smith", email: "jane.smith@example.com", role: "User" },
  { name: "Alice Johnson", email: "alice.johnson@example.com", role: "Editor" },
  { name: "Bob Brown", email: "bob.brown@example.com", role: "Moderator" },
  { name: "Charlie Davis", email: "charlie.davis@example.com", role: "User" },
  { name: "David Wilson", email: "david.wilson@example.com", role: "Admin" },
  { name: "Emma Thompson", email: "emma.thompson@example.com", role: "Editor" },
  { name: "Frank White", email: "frank.white@example.com", role: "User" },
  { name: "Grace Lee", email: "grace.lee@example.com", role: "Moderator" },
  { name: "Henry Clark", email: "henry.clark@example.com", role: "User" },
  { name: "Ivy Harris", email: "ivy.harris@example.com", role: "Admin" },
  { name: "Jack Martin", email: "jack.martin@example.com", role: "Editor" },
  { name: "Kate Lewis", email: "kate.lewis@example.com", role: "User" },
  { name: "Liam Walker", email: "liam.walker@example.com", role: "Moderator" },
  { name: "Mia Young", email: "mia.young@example.com", role: "User" },
  { name: "Noah King", email: "noah.king@example.com", role: "Admin" },
  { name: "Olivia Scott", email: "olivia.scott@example.com", role: "Editor" },
  { name: "Paul Hall", email: "paul.hall@example.com", role: "User" },
  { name: "Quinn Allen", email: "quinn.allen@example.com", role: "Moderator" },
  { name: "Rachel Wright", email: "rachel.wright@example.com", role: "User" },
  { name: "Sam Baker", email: "sam.baker@example.com", role: "Admin" },
  { name: "Tina Gonzalez", email: "tina.gonzalez@example.com", role: "Editor" },
  { name: "Uma Carter", email: "uma.carter@example.com", role: "User" },
  {
    name: "Victor Evans",
    email: "victor.evans@example.com",
    role: "Moderator",
  },
  { name: "Will Perez", email: "will.perez@example.com", role: "User" },
];
export default users;
